apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: docker-jenkins-integration-sample
spec:
  selector:
    matchLabels:
      app: docker-jenkins-integration-sample
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: docker-jenkins-integration-sample
    spec:
      containers:
        - name: docker-jenkins-integration-sample
          image: erumsajid/docker-jenkins-integration-sample # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster